<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tauri.Core\Tauri.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\GuildCharacters\" />
  </ItemGroup>
</Project>
